### ISSUE TITLE
Airdrop

### ISSUE THREAD

**Issue by Brian369** [tarassh/fairy-wallet#10]
Once I selected my airdrop, I don't see any amount of airdrops related to it.
How do I transfer my airdrops from greymass to fairy-wallet?

**Comment by tarassh** [comment]
<img width="283" alt="image" src="https://user-images.githubusercontent.com/5903550/45104747-7346b280-b13b-11e8-89df-a6ee387ab03d.png">
You can add airdrop from here. Press `+` button. And select airdrop you want to track.

<img width="520" alt="image" src="https://user-images.githubusercontent.com/5903550/45104873-a25d2400-b13b-11e8-8920-341e5716b3d3.png">

**Comment by tarassh** [comment]
Can I close it?

**Comment by Brian369** [comment]
Hi Tarassh,

In the attachment you will see what I mean. I have included three airdrops and none of  these have the numbers of token that I have got.

Karma  (7291); Horus (910); IQ (4131)

So why my tokens aren’t there?

 

Thanks

 

F; IQ (4131)rom: tarassh <notifications@github.com> 
Sent: September 5, 2018 14:38
To: tarassh/fairy-wallet <fairy-wallet@noreply.github.com>
Cc: Brian369 <brian.leclerc@bell.net>; Author <author@noreply.github.com>
Subject: Re: [tarassh/fairy-wallet] Airdrop (#10)

 

Can I close it?

**Comment by tarassh** [comment]
I don't see the attachment.
Could you also try change endpoint.

**Comment by Brian369** [comment]
Here it is. 

What do you mean by ‘try change endpoint’?

**Comment by tarassh** [comment]
Here is the list: https://github.com/tarassh/fairy-wallet/wiki/Connect-to-Mainnet

**Comment by Brian369** [comment]
I know that list. It doesn’t say why I don’t see the amount of tokens related to each airdorps and to correct the situation.

Do you know why and how?

**Comment by tarassh** [comment]
The tokens are not visible by default. You have to add them, the functionality is similar to greymwass wallet.

And unfortunately I don't see the attachment, are you replaying from the GitHub directly? 
Can you tell, what account name do you have?

**Comment by Brian369** [comment]
How do I add them ?

The attachment shows 3 airdrops with 0:00 tokens which in fact I have a number of airdrops tokens in each of them.

What do you mean ‘are you replaying from the GitHub directly’?
