### ISSUE TITLE
Permissions Tab in FairyWallet

### ISSUE THREAD

**Issue by redsky015** [tarassh/fairy-wallet#108]
Hi, what does the permissions tab do in the FairyWallet?  I'm confused.  Thanks.

**Comment by redsky015** [comment]
When I open up the permissions tab, it shows a key under active and owner.  What is this key?  and what is the permissions tab used for?  Thanks again.

**Comment by tarassh** [comment]
Those are public keys.

**Comment by tarassh** [comment]
Permission tab is used to change keys, active and owner permissions.

**Comment by redsky015** [comment]
Ok, thanks!  What is fairwallet.io?

**Comment by tarassh** [comment]
fairywallet.io is web version of the wallet.

**Comment by redsky015** [comment]
Ok, thanks.  Is it ready to use?

**Comment by tarassh** [comment]
Ledger devices, yes.
