### ISSUE TITLE
Fairy Wallet won't open when EOS app on Ledger is selected

### ISSUE THREAD

**Issue by lumierephoto** [tarassh/fairy-wallet#11]
Following the directions in the WIKI, I'm at the step where I connect to the Mainnet. 

Only for me, the steps are produced differently. First I'm asked to connect my Ledger. Then I'm asked to open the EOS application on the Ledger. 

When I open the EOS application, nothing happens so therefore I'm stuck at this step.

**Comment by lumierephoto** [comment]
![screen shot 2018-09-05 at 1 09 19 pm](https://user-images.githubusercontent.com/981541/45112329-f3095880-b10c-11e8-9ade-55e1a1e77333.png)
This is the screen that I'm stuck on. I've opened the EOS app, but nothing happens and stuck at this screen.

**Comment by Ahnde** [comment]
Same for me

**Comment by tarassh** [comment]
what OS do you use?

**Comment by lumierephoto** [comment]
Mac OS High Sierra  10.13.6

**Comment by tarassh** [comment]
What firmware you have on Ledger? 1.4.2?

**Comment by Ahnde** [comment]
In my case windows 10 and ledger 1.4.2

**Comment by Ahnde** [comment]
Testet it with MacOS, too.
There I have the same screen as @lumierephoto. Nothing happens then.

**Comment by lumierephoto** [comment]
Yes, I have 1.4.2 that I installed using Ledger Live.

**Comment by lumierephoto** [comment]
I opened it up again last night and it worked!  I'm not sure what the issue was. This time the app asked for the link to the mainnet and then I was in.

I also tested moving my EOS from SimplEOS wallet to the Fairy Wallet. Will move the rest of the coins after the unstaking process takes place.

**Comment by Ahnde** [comment]
Worked for me too. The trick was to retry it twice, i.e. first I opened the fairy-wallet app, then I entered the EOS app on the ledger, disconnected the ledger and opened the EOS app on it again.

**Comment by fahid1** [comment]
> Worked for me too. The trick was to retry it twice, i.e. first I opened the fairy-wallet app, then I entered the EOS app on the ledger, disconnected the ledger and opened the EOS app on it again.

It worked.

**Comment by MiguelPachecoEOS** [comment]
Hi,

I have the same issue but I have kept trying several times and still with no access. Did somebody find another solution? 

Thank you all,
Miguel

**Comment by lumierephoto** [comment]
> Hi,
> 
> I have the same issue but I have kept trying several times and still with no access. Did somebody find another solution?
> 
> Thank you all,
> Miguel

I would keep trying and toying with it. It's kind of buggy software, but it does work. Just keep plugging and unplugging the Ledger and it should start working.

**Comment by tarassh** [comment]
> Hi,
> 
> I have the same issue but I have kept trying several times and still with no access. Did somebody find another solution?
> 
> Thank you all,
> Miguel

1. First, you have to launch FairyWallet,
so you should be able to see ledger image as below:
<img width="542" alt="image" src="https://user-images.githubusercontent.com/5903550/48840049-397a6500-ed96-11e8-9435-82dd9909a83d.png">
2. Now, you should plug in and unlock the device. Once it unlocked Ledger image should change to image below (on windows it may take more time).
<img width="483" alt="image" src="https://user-images.githubusercontent.com/5903550/48840205-aa218180-ed96-11e8-8163-662adf924653.png">
3. The last one, you have to select and launch Eos application on ledger, and after that wallet will be unlocked.


If its not working, try to change usb cable, we had few users when it helped.

**Comment by MiguelPachecoEOS** [comment]
Thanks a lot to everybody.

The solution in my case was to use the original ledger nano cable. This was weird as I tried with 3 different cables and I could see/manipulate other wallets but not the Fairy Wallet one.

Happy days now, thanks again.
Miguel,

**Comment by Stormn12** [comment]
This thread is closed? If so what a pity. Just in case . . . I tried everything suggested in this thread with no success for over 3 hours off and on. I bought various crypto coins (including EOS) and a Ledger Nano S (yes, firmware is uptodate) some three years ago. My first shot at using my ledger nano s and here I am - disappointed that Ledger would include this buggy fairy wallet in their help/faq section with this 3 year history. Yes, I've even tried another USB.

Sometimes I get the msg "cannot read device properties, make sure . . .etc". Sometimes the Fairy wallet looks to be looking for an https node to no avail. Sometimes my device will ask me if I want to uninstall (all) apps.

Good news: it's forced me to open an account with Github, the idea of which this non-programmer has toyed with over the last couple of years. Can anyone help? I can assure you it would be most appreciated.
