### ISSUE TITLE
Unable to send EBT token using EOS fiarywallet app

### ISSUE THREAD

**Issue by GreenAces** [tarassh/fairy-wallet#15]
I installed the EOS fiary wallet app and Ledger Live app with the latest version. My problem is when I try to send an EOS token to another EOS account, the transaction fails. The error I receive is "failed packed transactions"
The EOS token I'm trying to send is: EBT
the EOS contract: theeosbutton
I've concluded that this problem only occurs with the EBT token because when I try to send a different EOS token to another EOS account, the transaction is successful. Therefore, how do I proceed on fixing the problem?

**Comment by tarassh** [comment]
Different EOS token, like KARMA, etc. Right?

**Comment by GreenAces** [comment]
Right
________________________________

**Comment by tarassh** [comment]
This error is specific to token. Maybe it has some fees.

**Comment by tarassh** [comment]
Duplicate of #36
