### ISSUE TITLE
Can't undelegate "src property must be a valid json object"

### ISSUE THREAD

**Issue by phillyman2633** [tarassh/fairy-wallet#150]
When I try to undelegate my EOS, I receive an error that says "src property must be a valid json object."  This is obviously an issue as I can't access my funds.  How do I fix this?  I have tried multiple nodes with no success.

**Comment by nico33fr** [comment]
Hello, I have the same problem as you with my Ledger X. There's nothing I can do!!!

**Comment by paboowicz** [comment]
i have the same problem, ledger nano s

**Comment by andyztefanie** [comment]
having the same problem. Trying to undelegate eos i taked long time ago.

**Comment by Nyko1976** [comment]
Hello guys, you have solved the problem?

**Comment by nico33fr** [comment]
Hi,Yes, thank YouTube.RegardsEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : Nyko1976 ***@***.***> Date : 05/04/2021  19:35  (GMT+01:00) À : tarassh/fairy-wallet ***@***.***> Cc : nico33fr ***@***.***>, Comment ***@***.***> Objet : Re: [tarassh/fairy-wallet] Can't undelegate "src property must be a valid json object" (#150) 
Hello guys, you have solved the problem?

**Comment by mephistophelesbits** [comment]
I have the same problem. Any solution?

**Comment by phillyman2633** [comment]
Nah they don't care enough to respond. I emailed Ledger support and told them they shouldn't back an unsupported wallet as their official EOS solution and they said they have received plenty of complaints and are exploring other options.
