### ISSUE TITLE
how to recover EOS from Ledger Nano S

### ISSUE THREAD

**Issue by viguerbe** [tarassh/fairy-wallet#151]
Dear community,

Message from a total newbie:

3 years ago I stored EOS coins on my Ledger Nano S. In the current context I felt the need for the first time to connect and potentially trade again my EOS. But my memory is failing me and I don't remember how I stored them on the Ledger (cannot remember the tool nor things like the EOS account used), and I don't know how to retrieve it (not as straightforward as with my other currencies through Ledger Live).

I've tried following tutorials (like the one below) with no success, and honestly I'm not clear on what I am doing and I'm afraid I might compromise my crypto assets.
https://www.reddit.com/r/eos/comments/9e2uri/how_to_use_your_current_eos_account_on_the_ledger/

What would be the easiest way to:
1. Check the EOS I have on my Nano S?
2. Retrieve it to a trading platform?

I do have my Ledger Pin code and recovery phrase.

Thanks for your assistance on this stressful topic.

**Comment by Rb0009** [comment]
Exact same story  , let me know if you find the solution.

**Comment by Hase2018** [comment]
I posted it before, had problems with Fairy wallet and Ledger Nano. Bloks.io worked instead of Fairy with my Ledger . I think that fairy is eol!

**Comment by Rb0009** [comment]
Thanks Hase ,  same problem on  bloks.io for me.  Can't see any EOS tokens.  I've been trying many things these last few days with no success. Tokens are lost on in my Ledger Nano S :((((

**Comment by janingve** [comment]
I have a similar problem. I opened an account on Blok.io but now what? Do I have to transfer my EOS from my Nano X to the Blok.io account then to Coinbase?  I want to get all of my EOS tokens out of my Nano X and I just don't get it regarding how I do that. Any help would be very appreciated.

**Comment by mehralfa** [comment]
Hello
I can not stake in my account with Ledger Nano S cpu and net! Every site and fairy wallet I try does not allow anything

![eos](https://user-images.githubusercontent.com/36608890/115009839-f6b70b80-9ec1-11eb-92cf-5eb94e8029eb.png)

**Comment by stefano-p** [comment]
This project is dead. Ledger support states that they have no control over this wallet. Beware they have no control over the EOS app either!!!

**Comment by DSPV555** [comment]
> I have a similar problem. I opened an account on Blok.io but now what? Do I have to transfer my EOS from my Nano X to the Blok.io account then to Coinbase? I want to get all of my EOS tokens out of my Nano X and I just don't get it regarding how I do that. Any help would be very appreciated.

Hi. Bloks.io (not blok.io). Log in with your ledger and you will instantly see you EOS coins balance. To transfer them. you need some resources: stake CPU and NET,  buy some RAM ( I staked 3 EOS in CPU, 3 EOS in NET and bought 2 EOS worth RAM). Indicate your account name (12 letters/digits) as a receiver (send some EOS to yourself) when staking CPU & NET and buying RAM. After that simply transfer your EOS to exchange: press "transfer" in the left upper corner and indicate both your EOS account address and MEMO (copy - paste them from the exchange). That's it.

**Comment by mehralfa** [comment]
> > I have a similar problem. I opened an account on Blok.io but now what? Do I have to transfer my EOS from my Nano X to the Blok.io account then to Coinbase? I want to get all of my EOS tokens out of my Nano X and I just don't get it regarding how I do that. Any help would be very appreciated.
> 
> Hi. Bloks.io (not blok.io). Log in with your ledger and you will instantly see you EOS coins balance. To transfer them. you need some resources: stake CPU and NET, buy some RAM ( I staked 3 EOS in CPU, 3 EOS in NET and bought 2 EOS worth RAM). Indicate your account name (12 letters/digits) as a receiver (send some EOS to yourself) when staking CPU & NET and buying RAM. After that simply transfer your EOS to exchange: press "transfer" in the left upper corner and indicate both your EOS account address and MEMO (copy - paste them from the exchange). That's it.

Dear friend, you helped me a lot. I was able to transfer all my eos .. Thank you very much

**Comment by viguerbe** [comment]
Thank you DSPV555

**Comment by Rb0009** [comment]
> Thank you DSPV555

Hi viguerbe ,  did you ever find you EOS tokens ?  My tokens never showed up on bloks.io  
Thanks
