### ISSUE TITLE
How to create multiple accounts using ledger?

### ISSUE THREAD

**Issue by HassanAmad** [tarassh/fairy-wallet#16]
I was able to go through the instructions and set up a single hardware wallet account. I need additional accounts, but there does not seem to be an option for that. How do we do this?

**Comment by tarassh** [comment]
You can create it using the service from DEXEOS
or any other service like:
https://eostoolkit.io/account/create
https://www.zeos.co
https://eos-account-creator.com

But you have to use the same public key.

**Comment by volschin** [comment]
This is only a workaround in my opinion and the issue should not be closed, but handled as needed enhancement. BIP44 delivers all to do so. It is sometimes not wanted to show same public keys on different accounts.
