### ISSUE TITLE
Trouble in sending tokens

### ISSUE THREAD

**Issue by Elcigno** [tarassh/fairy-wallet#19]
When I try to send tokens from my account, once I confirmed the transaction on my ledger, the following message appears: 
"assertion failure with message: symbol precision mismatch"
I think, I am not doing anything wrong, could anyone help me?(*)
Thanks a lot in advance.

(*) I am using the fairy wallet on iOS 10.13.5

**Comment by tarassh** [comment]
This error has nothing to Ledger. Blockchain rejected your transactions. What kind of tokens do you use?

**Comment by Elcigno** [comment]
Hi, thanks for your prompt reply.
I am trying to transfer IQ tokens from one account to another

**Comment by tarassh** [comment]
IQ has fee 0.1%

**Comment by tarassh** [comment]
IQ has fee 0.1%
