### ISSUE TITLE
Issue with voting

### ISSUE THREAD

**Issue by mortyblack** [tarassh/fairy-wallet#21]
Hi,
When I navigate to Vote tab it opens empty window

FairyWallet Version 0.9.1 (0.9.1)
MacOs High Sierra 10.13.2

**Comment by c1pca** [comment]
Hello,
try to change node:
https://eos.greymass.com - operated by Greymass or
https://eosbp.atticlab.net - operated by AtticLab

**Comment by mortyblack** [comment]
I have already tried to change it and open on windows and ubuntu.
