### ISSUE TITLE
Error in permissions doing any action 

### ISSUE THREAD

**Issue by gomadosnitro** [tarassh/fairy-wallet#23]
Hi i got this error every time trying to send,delegate,buying ram ,etc....

transaction declares authority '{"actor":"xxxxxxxxxxxxxxxxxx","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], and provided keys ["EOSxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]

i saw in a forum that can be resolved changing {"actor":"xxxxxxxxxxxxxxxxxx","permission":"active"}' to {"actor":"xxxxxxxxxxxxxxxxxx","permission":"owner"}'

buy i cant doit in the program to test it.

Can i extrat the private eos key  from my ledger?
How can i change permissions ?

ok something wrong creating the account key permission @active is different from @owner

the @ active permission is the key from my scatter account and the key @owner is from my ledger

can i send eos with owner instead active?

**Comment by tarassh** [comment]
Try new release 0.9.5, now you can choose owner permission for transaction.
