### ISSUE TITLE
Unable to send IQ token

### ISSUE THREAD

**Issue by MButcho** [tarassh/fairy-wallet#27]
Hello,
when sending IQ token via Ledger Nano S, I receive an error:
![image](https://user-images.githubusercontent.com/41790777/45585310-95ca8f80-b8e2-11e8-9fcb-9107e997cd17.png)

All other tokens were transfered without a problem

What can be done?

Thank you

MB

**Comment by tarassh** [comment]
IQ has transfer fee, try to send smaller amount

**Comment by MButcho** [comment]
I have 311 IQ there and tried to send 10 IQ, same error.

**Comment by c1pca** [comment]
#19 common issue

**Comment by c1pca** [comment]
Fixed in v0.9.3
