### ISSUE TITLE
everytime hit transfer button wallet goes white screen and nothing happens

### ISSUE THREAD

**Issue by kaptkorea** [tarassh/fairy-wallet#30]
every time hit transfer button wallet goes white screen and nothing happens

**Comment by kaptkorea** [comment]
nevermind.  have to have eos in acct before that window will open...so if you create new acct transfer some funds to it before opening transfer tab

**Comment by tarassh** [comment]
I am not sure, but may look like a UI bug. Was you able initiate transfer without specified amount of tokens?

**Comment by kaptkorea** [comment]
yes i did !  once i put some more eos in there it was fine.  i commented on
my own issue in case someone else runs into same issue.  thanks for
responding though !!  wallet is awesome w/ ledger !!

**Comment by PatBir** [comment]
I confirm the same bug...

**Comment by abovyanv** [comment]
I have the same issue, but I have 0 balance. If i send some tokens to account should it fix that bug? does anyone know?

**Comment by PatBir** [comment]
Exact !
I had 0.20 only on my account when i note that problem.
Now I have more than that and it works ! 
So it's a minor bug that disapear beyond a threshold...

**Comment by abovyanv** [comment]
cool, thanks! i hope they will fix that adding return button with describing how to fix that

**Comment by tarassh** [comment]
Fixed in 0.9.4
