### ISSUE TITLE
Unable to create an account

### ISSUE THREAD

**Issue by LouisWayne** [tarassh/fairy-wallet#31]
![capture_2018-09-16_15-24-19](https://user-images.githubusercontent.com/4606207/45600077-c7b42280-b9c4-11e8-97c9-d4f829a7b7e0.png)

I keep getting the above error message when I try to create a new account

**Comment by fisher2003** [comment]
I am getting the same error message. The system is not connecting with Paypal.

**Comment by c1pca** [comment]
**NOTE: This solution is optional**, You can use any other existing services to create an account. The primary requirement is to use public key retrieved from the device. Here is the list of other available services:

https://eostoolkit.io/account/create
https://www.zeos.co
https://eos-account-creator.com
