### ISSUE TITLE
Cannot purchase accout name

### ISSUE THREAD

**Issue by fisher2003** [tarassh/fairy-wallet#32]
I enter my new name the red info turns green then I try to create (pay with paypal) 
I get an error account creation failed

**Comment by fisher2003** [comment]
#25 does not help because I need to create an account to login.

**Comment by c1pca** [comment]
**### NOTE: This solution is optional**, You can use any other existing services to create an account. The primary requirement is to use public key retrieved from the device. Here is the list of other available services:

https://eostoolkit.io/account/create
https://www.zeos.co
https://eos-account-creator.com
