### ISSUE TITLE
Account History Section Not Displaying Full Memo Text for Transactions

### ISSUE THREAD

**Issue by Errol1886** [tarassh/fairy-wallet#35]
In the account "History" section, I have noticed that the "memo" text for transactions is not displaying the full text (the text is being cut off).

Here is a screenshot that shows this problem:

![not-displaying-full-memo-text](https://user-images.githubusercontent.com/41203384/45768728-a148ee00-bc35-11e8-9076-23458197e610.jpg)

**Comment by tarassh** [comment]
I would not consider this as an issue, as you can go to blockchain explorer to view tx details.
Memo field should be trimmed anyway, as EOS allows to have it way more longer.
Would you consider to read spam messages measured in megabytes?

**Comment by Errol1886** [comment]
@tarassh 

I think you should allow for at least 3 paragraphs of text to be displayed within the Memo field as the text is even being cut off for airdrop messages. Having to click to open the blockchain explorer to view the full TX details is very annoying. Other EOS desktop wallets such as EOS Voter by Greymass let you see the full memo.

**Comment by tarassh** [comment]
Fixed in 0.9.5
