### ISSUE TITLE
Invalid Packed Transaction error occurs when trying to send EDNA tokens 

### ISSUE THREAD

**Issue by GreenAces** [tarassh/fairy-wallet#36]
When using the ledger nano s on ubuntu 16.04 LTS, I get an error regarding a "Invalid Packed Transaction." This occurs when I try to send the EDNA token.

**Ledger Live version 1.1.11_amd64
   Fairy-wallet version 0.9.3_amd64**

**Error in complete details:**

Transaction Failed

Transfer funds
Invalid Packed Transaction
{
"code":500
"message":"Internal Service Error"
"error":{
"code":3010010
"name":"packed_transaction_type_exception"
"what":"Invalid packed transaction"
"details":[
0:{
"message":"Invalid packed transaction"
"file":"chain_plugin.cpp"
"line_number":1401
"method":"push_transaction"
}
1:{
"message":"pivot != std::string::npos: No delimiter in string, cannot determine type: 9000"
"file":"signature.cpp"
"line_number":20
"method":"parse_base58"
}
2:{
"message":"error parsing signature"
"file":"signature.cpp"
"line_number":28
"method":"parse_base58"
}
3:{
"message":"Failed to deserialize variant"
"file":"abi_serializer.hpp"
"line_number":608
"method":"from_variant"
}
]
}
}

**Comment by tarassh** [comment]
Fixed in 0.9.5

**Comment by GreenAces** [comment]
Thank you! :)
