### ISSUE TITLE
Only 11 tokens are displayed in the selection menu when a user wants to transfer funds.

### ISSUE THREAD

**Issue by GreenAces** [tarassh/fairy-wallet#39]
![selection_001](https://user-images.githubusercontent.com/20262218/45847319-ae7ae100-bcf8-11e8-9bc0-2ca84bd700a9.png)

**Ledger Live version 1.1.11_amd64
Fairy-wallet version 0.9.5_amd64**

Only 11 tokens are displayed in the selection menu when a user wants to transfer funds. Please allow up to the total amount that is available for the EOS account. **A scroll down menu would be nice**. Currently the only way a user can send tokens that are not displayed in the selection menu is to delete the 11th token to make room for the new token. It's not a big problem but it's kinda annoying  :100:

**Comment by tarassh** [comment]
fixed 0.9.6

**Comment by GreenAces** [comment]
Thanks! Contact list is awesome by the way! :+1:

**Comment by tarassh** [comment]
Thanks, What about fiat equivalent?

**Comment by GreenAces** [comment]
I was wondering what that empty field was lol. I needs to be fixed. I will open a new issue soon
