### ISSUE TITLE
Import existing accounts

### ISSUE THREAD

**Issue by geldmacher** [tarassh/fairy-wallet#4]
Any plans on importing existing EOS accounts?

**Comment by eosimpera** [comment]
You can just use the generated key from the ledger and change the permission from an existing wallet

**Comment by plouto5** [comment]
is it possible to add more than one account?

**Comment by geldmacher** [comment]
@eosimpera Thx!

Do you know any documentation about "changing permission of existing wallet" i can read? Atm I do not know what you mean. ;D

**Comment by tarassh** [comment]
@plouto5 yes, just use the same key for account registration.

**Comment by geldmacher** [comment]
As far as I understood it now, it should be possible to change owner and active permission of another account to the public key generated via ledger/fairy wallet. After this i should have access to this account via fairy wallet. 

Example: https://eosio.stackexchange.com/questions/832/how-to-transfer-ownership-of-an-account-to-another-eos-key-pair

Am I right? :)

**Comment by MonkeyCrushR** [comment]
But would you not need the PRIVATE KEY as well related to the Ledger wallet? If you simply change an existing account's OWNER key to the Public Key in the Ledger, you will never again be able to remove that account from Ledger and use it in Scatter, etc. Further, if you use the Ledger Public Key as the Active Key for an existing account, you really would not control the OWNER permissions in the Ledger itself for that account, as the Owner keys would be a level ABOVE the Ledger, wouldn't they?

**Comment by geldmacher** [comment]
Yes, this sounds right! 

If Fairy wallet would get some sort of interface for managing permissions via the Ledger private Key this "problem" should be solved.

**Comment by volschin** [comment]
At the moment it would be no good idea to change the OWNER key of an account to Ledger Namo S, because it is a one way without return, as there is no application you would be able to change tis back.
I would suggest to wait until Fairy Wallet or another app has this permission management implemented.

**Comment by steveharman** [comment]
Assuming the EOS app is installed on the Ledger and I've gone through the public-key verification step to establish what's on my Mac's screen is the same as on the Ledger's display - is it a _requirement_ to create another new EOS account?  

The videos I've watched seem a little unclear. https://www.youtube.com/channel/UCnXofUeO5w1dO9JGWWDdqPQ 

- Video 1 "EOS Ledger Setup" goes through the initial app installation on the Ledger and includes steps to create an EOS account. 
- Video 2 "Import an Existing EOS Account" shows how to associate an existing EOS account with the Ledger _after_ having gone through Video 1.

But I can't find mention of whether it's possible to go straight from "Verify the public key on the Ledger [in Video 1] >> now associate that key with your existing account's Active permission [in Video 2]" and cut out the creation of a new EOS account.

Thanks

**Comment by pdarcos** [comment]
Why was this issue closed.
This is a pretty important feature that I'm sure will interest lots of people (including me).

After reading the whole thread I'm still confused if it's possible to import and existing EOS account or not.

Any help?

**Comment by volschin** [comment]
Check the Greymass Wallet. You can easily Login to your account there and update it to the ledgers Key.

**Comment by pdarcos** [comment]
Thanks @volschin 
I'll try that
