### ISSUE TITLE
当nanos的public key只绑定了一个owner key时，无法发送交易

### ISSUE THREAD

**Issue by ly82505129** [tarassh/fairy-wallet#40]
`{
  "code": 500,
  "message": "Internal Service Error",
  "error": {
    "code": 3090003,
    "name": "unsatisfied_authorization",
    "what": "Provided keys, permissions, and delays do not satisfy declared authorizations",
    "details": [
      {
        "message": "transaction declares authority '{\"actor\":\"XXXXXXXX\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], provided keys [\"XXXXXXXX\"], and a delay max limit of 3888000000 ms",
        "file": "authorization_manager.cpp",
        "line_number": 413,
        "method": "check_authorization"
      }
    ]
  }
}`
1.当只绑定了一个owner key时，无法发送交易和执行其他操作，这应该是一个bug
2.通过scatter，只有连接成功时可以发送一笔交易，之后也无法发送交易

**Comment by tarassh** [comment]
Do you have both permissions (active and owner) bound to your device?

**Comment by tarassh** [comment]
If I got you right. In order to sent transaction with owner permission you should select it before doing the transaction

<img width="348" alt="image" src="https://user-images.githubusercontent.com/5903550/45903660-27f6fa00-bdf3-11e8-93b7-51ab4c5089e8.png">

**Comment by ly82505129** [comment]
> 如果我找对你 为了使用所有者权限发送事务，您应该在执行事务之前选择它
> 
> <img alt="图片" width="348" src="https://user-images.githubusercontent.com/5903550/45903660-27f6fa00-bdf3-11e8-93b7-51ab4c5089e8.png">

我只绑定了owner key，active key绑定了其他的公钥地址。
我没找到你图片中的按钮

![_20180922125506](https://user-images.githubusercontent.com/5029547/45913540-fb7cc580-be66-11e8-9068-0080ed7457a2.png)

**Comment by ly82505129** [comment]
![_20180922125506](https://user-images.githubusercontent.com/5029547/45913543-0a637800-be67-11e8-8589-981f82f6bb43.png)

**Comment by ly82505129** [comment]
OK，我更新了0.9.5版本之后可以选择当前的权限，交易发送正常了，非常感谢
