### ISSUE TITLE
Can't Use Transferred Account

### ISSUE THREAD

**Issue by ManveerJarosz** [tarassh/fairy-wallet#41]
For my snapshot EOS account, I changed both the _owner_ and _active_ key to my Ledger Nano's / FairyWallet's public key.

The account is now showing up in my FairyWallet, but I cannot complete any transactions with it. For any transaction I confirm with my Ledger Nano, I get the following error:

> transaction declares authority '{"actor":"xxxxxxxxxxxx","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], provided keys ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"], and a delay max limit of 3888000000 ms

**Comment by ManveerJarosz** [comment]
Ah, looks like the issue is that only the _owner_ key was successfully updated. The _active_ key was still set to the old one. Once I updated the _active_ key everything started to work.

**Comment by tarassh** [comment]
Actually, you can execute transaction under owner key as well, you have explicitly set it to owner like on the screen shot 

<img width="258" alt="image" src="https://user-images.githubusercontent.com/5903550/45913324-e7ba6a80-be38-11e8-9240-09b0d5d80c57.png">

**Comment by ManveerJarosz** [comment]
Weird, my FairyWallet looks different:
- The color scheme is light/white
- There is no dropdown next to the Transfer button

And I don't see any settings/preferences to change either of these. How'd you get this?

**Comment by tarassh** [comment]
Update to 0.9.5

**Comment by ManveerJarosz** [comment]
Ah that explains it, thank you! <3

I downloaded FairyWallet that same day though. Looks like the download link in the wiki is outdated and directing new users to 0.9.1: https://github.com/tarassh/fairy-wallet/wiki/Install-the-Fairy-wallet-application

Feature request: have the wallet notify us if/when there is an update.

**Comment by tarassh** [comment]
That feature is in my mind. Unfortunately, I cannot scale, don’t know when I’ll get my hands on it.  :/
