### ISSUE TITLE
Undefined error is displayed near EOS token balance and stalked balance

### ISSUE THREAD

**Issue by GreenAces** [tarassh/fairy-wallet#44]
version: fairy-wallet_0.9.6_amd64
ledger live version: 1.1.11_amd64
operating system: Ubuntu 16.04 LTS

![selection_003](https://user-images.githubusercontent.com/20262218/46052384-38b5b180-c10c-11e8-8048-4092f2dc50a8.png)

'Undefined' error is displayed near EOS token balance and stalked balance as seen in screenshot above, however I know this is incorrect because using bloks.io confirms EOS token and stalked balance  are valid for my EOS account.

**Comment by tarassh** [comment]
Can you go to settings tab, and choose switch currency. That should be as an workaround for now.

**Comment by tarassh** [comment]
Fixed https://github.com/tarassh/fairy-wallet/releases/tag/v0.10.0
