### ISSUE TITLE
Dapp signing 

### ISSUE THREAD

**Issue by plouto5** [tarassh/fairy-wallet#46]
Can't sign transactions from dapps

**Comment by tarassh** [comment]
Wallet doesn't support dapps.

**Comment by plouto5** [comment]
https://github.com/GetScatter/ScatterDesktop/issues/91#issuecomment-426475460

Any plan on adding the action to allow for the signing of transaction actions than what is currently possible?

**Comment by plouto5** [comment]
Thank you for the detailed response and your great work!
