### ISSUE TITLE
Permission management with Ledger

### ISSUE THREAD

**Issue by lexust1** [tarassh/fairy-wallet#48]
When are you going to add option for managing permissions via the Ledger private key? Now I feel uncomfortable when I need to use my private key in EOS-Voter for example in order to connect Ledger and Fairy Wallet.

**Comment by tarassh** [comment]
If I understand you right, migrating already existing account cannot be done from Ledger. Changing permission is possible with a key that have control over account. So, you have to use existing private key for that.

Ledger permission management feature will only work with accounts that are already bound to Ledger. 
And Is in progress right now.

**Comment by andrejcibik** [comment]
I second this. Without in-app option tomanage permissions, Ledger support is basically useless for people who want it only as a backup in case active key is compromised.

**Comment by roxanne1235** [comment]
Hi tarassh,  did I read that correctly,  the wallet will soon be able to change permissions ?

**Comment by tarassh** [comment]
Yes, I am working on it.

**Comment by roxanne1235** [comment]
it would also be good to be able to vote for a proxy too.  Thanks

**Comment by tarassh** [comment]
proxy is a part of the update, and other features.

**Comment by roxanne1235** [comment]
Thats such good news. Thank you

**Comment by tarassh** [comment]
Done https://github.com/tarassh/fairy-wallet/releases/tag/v0.10.0

**Comment by roxanne1235** [comment]
Hi, That was quick.
I downloaded the latest release but can't seem to change the permission.  
It says " ledger device invalid data "
Any ideas ?


    On Thursday, 8 November 2018, 09:16:55 GMT, tarassh <notifications@github.com> wrote:  
 
 
Done https://github.com/tarassh/fairy-wallet/releases/tag/v0.10.0

**Comment by roxanne1235** [comment]
Ignore my last email. I hadn't changed settings on ledger.  Well done on the update.
    On Thursday, 8 November 2018, 09:16:55 GMT, tarassh <notifications@github.com> wrote:  
 
 
Done https://github.com/tarassh/fairy-wallet/releases/tag/v0.10.0

**Comment by andrejcibik** [comment]
Huge thanks @tarassh ! What is the safe account for donations?

**Comment by iwanair** [comment]
Hi tarassh, just installed fairy wallet yesterday and it looks very easy to implement or add accounts for example my (never touched since june) eos genesis account with permissions. But not sure if I will do it right, and before I screw things up I was wondering where I could find an explanation of how it works. Could you let me know where I can find this?
Thanks a lot!
Iwan

**Comment by tarassh** [comment]
@iwanair https://medium.com/coinmonks/eos-permission-management-2c0c1634fe39

**Comment by iwanair** [comment]
Thanks for that, so it's no that simple to just use permissions in fairy wallet to add my genesis account? Will have a good look over the weekend again when there is more time.
Thanks

**Comment by tarassh** [comment]
Fairy Wallet works with hardware devices and accounts tied to keys on those devices. If your account is not tied to ledger, than you have to change permissions using other software.

**Comment by iwanair** [comment]
My genesis account was on my ledger nano s and never touched since...
Does that make things easier?
