### ISSUE TITLE
Refund action not supported

### ISSUE THREAD

**Issue by PiranhaUK** [tarassh/fairy-wallet#53]
Do you plan on supporting the refund command?

I have an EOS account that uses the Ledger for both the Active & Owner key and after unstaking 4 days ago it's now stuck "Refunding" and I'm unable to issue the "Refund" action to "Unstick" it....

Alternatively if we get account permissions working soon I can change the Active key to a Scatter generated key and then issue the refund using a web based wallet.

**Comment by tarassh** [comment]
New functionality, Refund and Permission management, is currently in review by Ledger. So we have to wait for the approval.

**Comment by PiranhaUK** [comment]
Brilliant news!

**Comment by PiranhaUK** [comment]
@comfyowl You can stake a small amount to CPU/NET and then unstake again immediately after (0.0001 EOS worked for me) - After 3 days you’ll then recieve your EOS refund including the stuck EOS 👍

Not ideal, but a decent work-around until refunds are supported on Ledger.

**Comment by comfyowl** [comment]
Thanks. I'm trying it right now. I will post the result after.

**Comment by tarassh** [comment]
Please download new version. https://github.com/tarassh/fairy-wallet/releases/tag/v0.10.0
