### ISSUE TITLE
Staked tokens not being shown

### ISSUE THREAD

**Issue by nunoarruda** [tarassh/fairy-wallet#58]
I have 0.2 of Staked tokens in my EOS account...
<img width="297" alt="screenshot 2018-10-31 at 11 19 48" src="https://user-images.githubusercontent.com/1189149/47787652-13b1f100-dcff-11e8-9c56-11a0c896f6c7.png">

...but it does not show in the FairyWallet:
<img width="757" alt="screenshot 2018-10-31 at 11 22 18" src="https://user-images.githubusercontent.com/1189149/47787720-40fe9f00-dcff-11e8-9a87-2f47aa13f745.png">
 
I've tried using different Nodes and different blockchain explorers in the settings but my Staked tokens are still zero.

What could be the issue here? Thanks in advance.

**Comment by tarassh** [comment]
same issue as #54. I will close this one.
