### ISSUE TITLE
uninstall fairy wallet?

### ISSUE THREAD

**Issue by kimmymex** [tarassh/fairy-wallet#59]
Hello!  
I installed fairy wallet and created a new account with a new account creator tool.  All went well.  
The trouble is...I should have imported my existing EOS account.  
Can I un-install fairy wallet and EOS app from ledger and then reinstall with the correct account?
Thanks so much for confirmation on this!

**Comment by tarassh** [comment]
Wallet is just a UI client to your account, which is located on the blockchain. So you have to link existing account to ledger public key.
