### ISSUE TITLE
Fairy Wallet does not pick up last transaction

### ISSUE THREAD

**Issue by TidoB** [tarassh/fairy-wallet#6]
I changed my EOS test account keys to the key provided by the Ledger Wallet and imported the account into Fairy Wallet. I sent 1 EOS from my main account to the test account, but the transaction does not show in Fairy Wallet. All previous transactions are shown, and my balance is still at 0 EOS. The transaction has been confirmed and block explorers show the account balance at 1 EOS, but Fairy Wallet does not seem to update and now it's impossible to send EOS from my test account - because the balance is zero. It's been a couple of hours and I have restarted the app but nothing seems to work.

Using version 0.9.0 on Ubuntu.

**Comment by c1pca** [comment]
Hello, 
try to change node:
https://eos.greymass.com - operated by Greymass or
https://eosbp.atticlab.net - operated by AtticLab

**Comment by TidoB** [comment]
That worked, thanks!

I restarted and changed the node from http://api.cypherglass.com/ to https://eosbp.atticlab.net/, and it showed the last transaction, but didn't update the balance. Then I restarted again and changed to https://eos.greymass.com/ and now the balance is correct.

**Comment by foobarninja** [comment]
+1 on the issue @TidoB reported. I had the exact same issue and resolution steps.
