### ISSUE TITLE
Error updating authorisation

### ISSUE THREAD

**Issue by Abrooksdavis** [tarassh/fairy-wallet#64]
Changing permissions using ledger does not work for me, I get the  following error.   I also get no prompt on my ledger device to accept the changes
![qqq](https://user-images.githubusercontent.com/44908116/48283922-e16a6700-e455-11e8-8381-ed4e19ad98ae.JPG)

The exact error is as follows:

"ERROR":{
"message":"src property must be a valid json object"
}

**Comment by Errol1886** [comment]
@Abrooksdavis 

On your Ledger Nano S, Open the EOS app, and in the Settings menu in the EOS app, Select "Arbitrary data", and then select "Yes".

Once you have done that, try changing permissions again.

**Comment by Abrooksdavis** [comment]
Yes! I Just tried that, had to restart the ledger device then after a few attempts to change my active key it was finnally accepted. Think I may have also had some connection issues.

Pleased to say everything is working great now
