### ISSUE TITLE
Greymass node - 'Bad Gateway

### ISSUE THREAD

**Issue by cryptoack** [tarassh/fairy-wallet#68]
When I try to sign in using my usual Greymass node, it says 'Failed to connect - bad gateway'
I tried using another node but (cypherglass) but this said 'Failed to fetch'
My ledger is on and I am in my eos app.
Can anyone help as I need to transfer some eos onto an exchange
Thanks

**Comment by Errol1886** [comment]
@cryptoack 

This node works: **https://eosbp.atticlab.net**

**Comment by cryptoack** [comment]
Thanks Errol much appreciated
