### ISSUE TITLE
Unable to Delegate EOS tokens

### ISSUE THREAD

**Issue by WolfFyonn** [tarassh/fairy-wallet#69]
Hi,

I started a new EOS account.

I can access the account with the Nano Ledger but it fails to sign the transaction. 

It confirms delegation on the ledger but the transaction fails.

Both keys appear the same on Bloks.io

Using Cypherclass  API

Have i set something up wrong?

Tried voting using another ledger on different account. Transaction also failed.

Any ideas.

**Comment by tarassh** [comment]
Can you show the error.

**Comment by EOS-Landix** [comment]
Try another node. I was having the same issue using EOS Dublin. Switched to Greymass and have not had any problems since.

**Comment by EOS-Landix** [comment]
Try another node. I switched nodes and it solved the same issue.

**Comment by WolfFyonn** [comment]
Switched nodes and worked
