### ISSUE TITLE
Assuming change active key is on the roadmap?

### ISSUE THREAD

**Issue by bitgenstein** [tarassh/fairy-wallet#7]
EOS is, as we all know, much more useful if cold holding owner key and using the active key for hot applications. Currently, if someone happens to change both the active and owner keys for their account to their Ledger key, there's no way to set a new active key for the account. Any chance this functionality is on the near-term roadmap?

**Comment by tarassh** [comment]
We are thinking about it. The feature requires extra caution and depends on Ledger monthly updates. We have to implement feature on the device as well.

**Comment by funkwizard** [comment]
Does Fairy Wallet not work at all if **only** the active key of an existing account is updated to the Ledger key?  I would have thought that the account functionality relating to active key permissions would still work in this case.

**Comment by tarassh** [comment]
https://github.com/tarassh/fairy-wallet/releases/tag/v0.10.0
