### ISSUE TITLE
Voting Tab Blank

### ISSUE THREAD

**Issue by douglasdeodato** [tarassh/fairy-wallet#72]
Hi,
When I navigate to Vote tab it opens empty window

I had changed for other nodes and I still getting the same error, where I can get the log error from the app?

**Comment by jackbarth** [comment]
This happened to me as well. And it did not allow me to stake either when using ledger.  It just kept spinning. I logged off ledger and shut down the app. If I plan to hodl, should I be staking?

**Comment by miguelmarron** [comment]
I get the same thing. Blank screen on voting tab.

**Comment by tarassh** [comment]
I am using https://eos.greymass.com and wallet version v0.10.0, seems to work without issues.

**Comment by StarryJapanNight** [comment]
I have a blank screen on the Permissions window. All other windows are fine.

**Comment by redsky015** [comment]
I have a blank screen on the voting tab also.  Will this issue be addressed?  I would like to vote for block producers only using my ledger and not expose my private key.  Thanks.

**Comment by tarassh** [comment]
Yes

**Comment by mickvalens23** [comment]
I have the same problem, I've never voted so I might be missing all airdrops. Can you kindly advise how to resolve this issue? thank you

**Comment by andreww127** [comment]
I have a blank screen on the voting tab, is this an issue with the application?

**Comment by Adamhazard** [comment]
I have the same issue. Click on VOTING tab causes a blank page to appear.  I have to restart wallet every time to get out of the blank screen.

**Comment by Makazar** [comment]
Same issue here. 4 months since the first post? Anybody even trying to resolve this?

**Comment by douglasdeodato** [comment]
> Same issue here. 4 months since the first post? Anybody even trying to resolve this?

I stopped use this software, because has loads of bugs, I am connecting my ledger nano s using: 

https://bloks.io

works like a charm, 

I will close this issue, because looks like a abandoned project.

**Comment by Makazar** [comment]
Thanks @douglasdeodato. That is really helpful.
