### ISSUE TITLE
Failed to Connnect

### ISSUE THREAD

**Issue by johnschenk** [tarassh/fairy-wallet#78]
I've tried connecting 10 times now. Thoughts?
<img width="521" alt="screen shot 2018-12-14 at 12 24 41 pm" src="https://user-images.githubusercontent.com/24555246/50025752-6ab41280-ff9b-11e8-9cd4-0ce3f899cdd8.png">

**Comment by tarassh** [comment]
Use other api, cypherglass isn’t working. atticlab or greymass.
