### ISSUE TITLE
Problem with setting up my fairy wallet

### ISSUE THREAD

**Issue by ColinApples** [tarassh/fairy-wallet#82]
I went through all the steps of setting up the fairy wallet but on the Create Account page, although it said 'Success Now click Login button', there was no visible login button. I have been through the steps of connecting the Fairy wallet to my Ledger. I tried to transfer 2 EOS to the public address provided but I have no idea whether that crypto has gone anywhere as I cannot access the Fairy wallet. Please help!

**Comment by ColinApples** [comment]
I've just discovered how to log in - by clicking on my user name - there was no login button.

**Comment by baeckera** [comment]
I have the same problem. Fair stops at step 2 after the account is created. No user can be clicked. Who knows advice?
