### ISSUE TITLE
Can I export my private key, so that I can integrate my account to Scatter and so on?

### ISSUE THREAD

**Issue by kyoungrok0517** [tarassh/fairy-wallet#9]
Can I export my private key, so that I can integrate my account to Scatter and so on? Or should I wait until the 3rd party apps support Ledger devices?

**Comment by tarassh** [comment]
You can use this site https://iancoleman.io/bip39/
to recover your private key.

But would not recommend to do that. Scatter is going to support the wallet.

**Comment by kyoungrok0517** [comment]
I see. Thanks!

**Comment by zbobyuan** [comment]
> You can use this site https://iancoleman.io/bip39/
> to recover your private key.
> 
> But would not recommend to do that. Scatter is going to support the wallet.

cannot find EOS in the coin list, which coin do I need to export private of EOS?

**Comment by Errol1886** [comment]
@zbobyuan 

Do not use the BIP39 Tool online. Download the BIP39 Tool from Ian Coleman's official GitHub: https://github.com/iancoleman/bip39/releases and disconnect your computer from the internet before opening the BIP39 Tool in your web browser. You should also check your PC for viruses/keyloggers before using the BIP39 tool.

1. In the BIP39 Tool, where it says BIP39 Mnemonic, enter your 24 word seed.

![image_1](https://user-images.githubusercontent.com/41203384/50666698-d4797800-0fad-11e9-9acf-8989153b5829.jpg)
2. Scroll down to section titled **Derivation Path**, and then click on the tab that is named **BIP32**, and then where it says **BIP32 Derivation Path**, enter m/44'/194'/0'/0/0 (which is the path to the first EOS public key address that is on your Ledger Nano S). 

![image_2](https://user-images.githubusercontent.com/41203384/50666582-57e69980-0fad-11e9-847c-d26465be9706.jpg)

Scroll down and in the **Derived Addresses** section, the EOS private key that is shown would be valid, but it's public key address would need to be converted from byte format to WIF format. I think you can use one of @tarassh tools to do this: https://github.com/tarassh/eos-ledger/blob/master/getPublicKey.py#L61 

Once you have converted the public key address to the format WIF, you would then need to validate the key pair of the extracted EOS private key and the converted to WIF format public key. You can use EOS Voter by Greymass (https://github.com/greymass/eos-voter/releases) to validate your EOS key pair.
